### ISSUE TITLE
Offer Linux 32bit for Raspberry Pi

### ISSUE THREAD

**Issue by wraybowling** [LightBurnSoftware/deployment#2]
Running laser cutter software on a single board computer that's always hooked up is an ideal situation in my mind. a Pi 4 is 64 bit, but all the older pi boards are 32 bit. Any chance of a 32-bit build so that Lightburn is pi-friendly?

**Comment by LightBurnSoftware** [comment]
Is there a reason you requested this on our deployment github, instead of emailing or posting in the forum?  This is a very weird place for a feature request.

To answer your question, we have no intention (or ability) to provide a version of LightBurn that will run on a PI.  Some of the libraries used simply aren't available for that platform, and the performance would be good enough for streaming, but probably quite bad for design.
